/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : EarlyAccessController
 * Author          : <YourName>
 * Created Date    : Aug 5, 2026
 * Last Modified By: <YourName>
 * Last Modified On: Aug 5, 2026
 * Description     : This class implements for......
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Aug 5, 2026  │ <YourName>   │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */

public class EarlyAccessController {

	@AuraEnabled(cacheable=true)
	public static void doSomething() {
		// Your logic here
	}

}