/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : TestController
 * Author          : <YourName>
 * Created Date    : Aug 7, 2026
 * Last Modified By: <YourName>
 * Last Modified On: Aug 7, 2026
 * Description     : This class implements for......
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Aug 7, 2026  │ <YourName>   │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */

public with sharing class TestController {

    @AuraEnabled(cacheable=true)
    public static String hello() {
        return 'Hello World';
    }
}